version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/online_clipboard
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - mongo
volumes:
  mongo_data:
